chore(ci): Upgrade dependencies and change package managers (#8397)
* Upgrade to Yarn Berry

Upgrade node to 18
Upgrade Typescript to 4.4.2

* Add yarn berry version in dockerfile

* Add missing yarn release file

* Fix volta yarn berry install

* Removing transpiled sms service

* Cleanup

* Upgrade apollo-server-express & graphql-codegen

* Add @apollo/gateway

* Add missing node-gyp

* Add missing postinstall

* Fix for: 'Resolvers<any>' does not satisfy the constraint 'ResolverMap'

* Fix broken imports

* Move graphql/@types, fix NextComponentType import

* Prettier and set fetch as global in jest for auth-admin-web

* Add new version of yarn lock

* Add whatwg-fetch for jest tests, allowjs for exportfinder

* Fixing builds and tests

* Fix tests to use restricted types

* Add --immutable to docker build, remove --no-experimental-fetch

* Fix lock file

* Node needs more juice

* Add missing node version in package.json

* Update cert for test cases to use ssl v3

* Fix various broken code

* Fix tests

* Fix typo

* Remove code-coverage and node-gyp

* Add node-gyp, use --immutable instead of frozen-lock

* Possible fix for 'AssertionError: Can not use queue until bootstrapping has finished'

* Remove deprecated test

* Use yarn berry cache

* Add missing forward slash

* Install python, move .yarn folder into build container

* Remove legacy .yarnrc

* Upgrade apollo client

* Revert "Upgrade apollo client"

This reverts commit 7d54eb67ac78d84a44dde2a762b06cc85d08a1d2.

* Fix missing Error: overallCachePolicy.policyIfCacheable is not a function

* Remove carats in package versions

* Remove unused test, remove IDE filled import, fix extensions typing

* Update apps/judicial-system/web/src/utils/validate.spec.ts

Co-authored-by: Arnar Kári Ágústsson <arnarkari93@gmail.com>

* Move "jest-environment-jsdom" to devDeps

* Fix merge conflicts in yarn.lock

* Update yarn.lock

* Fixing broken things from main

* Fix wrong JSON in test

* Prettier

* Give node more memory in next containers

* Add NODE_OPTIONS to docker-next

* Revert "Add NODE_OPTIONS to docker-next"

This reverts commit d91e6c0486130f5a2c3e67c0264f8fd7269cfe88.

* Revert "Give node more memory in next containers"

This reverts commit 6546f6415c0832c5f18f6de645c7963fa47c2e18.

* Increase executor memory

* Add memory limit

* Update yarn.lock after merge conflicts

* Add node memory limits to _common.sh

* Add back e2e test for air-discount-scheme

Co-authored-by: Brynjar <brynjar@andes.is>
Co-authored-by: Arnar Kári Ágústsson <arnarkari93@gmail.com>